package comerdormir.frontend;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import project.backend.empleado.Empleado;
import project.frontend.empleado.CreadorEncargadoR;
import project.frontend.empleado.CreadorGerenteG;
import project.frontend.empleado.CreadorGerenteH;
import project.frontend.empleado.ModificadorEmpleado;
import project.frontend.empleado.ReporteEmpleados;
import project.frontend.hotel.CreadorHotel;
import project.frontend.empleado.SolicitadorEmpleado;
import project.frontend.habitacion.CreadorHabitacion;
import project.frontend.habitacion.ModificadorHabitacion;
import project.frontend.habitacion.ReporteHabitaciones;
import project.frontend.hotel.DesactivarActivarHotel;
import project.frontend.hotel.ModificadorHotel;
import project.frontend.hotel.ReporteHotel;
import project.frontend.restaurante.CreadorRestaurante;
import project.frontend.restaurante.ModificadorRestaurante;
import project.frontend.restaurante.ReporteRestaurante;
//import project.alojamiento.frontend.*;
//import project.cliente.frontend.*;
//import project.menu.frontend.*;
//import project.consumo.frontend.ReporteConsumos;
//import project.habitacion.frontend.ModificadorPrecio;
//import project.reservacion.frontend.*;
//import project.usuario.Usuario;
//import project.usuario.frontend.*;

/**
 *
 * @author fabricio
 */
public class ComerDormirDesktop extends javax.swing.JFrame {

    private Empleado empleado = null;
    public static final String BACKGROUNDD_IMAGE_PARENT_RELATIVE_PATH = "src/project/frontend/images/";
    public static final String IMAGE_EXTENSION = ".jpg";
    public String path = " ";
    public String path1 = " ";
    private String tipoUsuario = " ";

    /**
     * Creates new form HotelDescktop
     */
    public ComerDormirDesktop(Empleado empleado) {
        this.empleado = empleado;
        setItems();
        initComponents();
        this.setLocationRelativeTo(this);
        visualizarItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanelBackground = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                ImageIcon im = new ImageIcon(path);
                Image i = im.getImage();
                g.drawImage(i, 0, 0, this.getSize().width, this.getSize().height, this);
            }
        };
        PrincipalDesktop = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                ImageIcon im = new ImageIcon(path1);
                Image i = im.getImage();
                g.drawImage(i, 0, 0, this.getSize().width, this.getSize().height, this);
            }
        };
        labelInformacion = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        jMenuGerente = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuHotel = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCrearUsuario = new javax.swing.JMenuItem();
        jMenuItemReporte = new javax.swing.JMenuItem();
        jMenuItemModificar = new javax.swing.JMenuItem();
        jMenuItemEliminar = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemCrearMenu = new javax.swing.JMenuItem();
        jMenuItemRepMenu = new javax.swing.JMenuItem();
        jMenuItemModMen = new javax.swing.JMenuItem();
        jMenuItemDeshaMenu = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItemModPre = new javax.swing.JMenuItem();
        jMenuRecepcion = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemRegistrar = new javax.swing.JMenuItem();
        jMenuItemElimRes = new javax.swing.JMenuItem();
        jMenuItemReportReser = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemRegAloj = new javax.swing.JMenuItem();
        jMenuItemRepAloj = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItemAlojHab = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemRegClie = new javax.swing.JMenuItem();
        jMenuItemModClie = new javax.swing.JMenuItem();
        jMenuItemRepClie = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuRestaurante = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItemTomarPed = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItemReporCon = new javax.swing.JMenuItem();
        jMenuOpciones = new javax.swing.JMenu();
        jMenuItemCambiar = new javax.swing.JMenuItem();
        jMenuItemSalir = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBackground.setPreferredSize(new java.awt.Dimension(1280, 720));

        labelInformacion.setFont(new java.awt.Font("Caviar Dreams", 1, 36)); // NOI18N
        labelInformacion.setForeground(new java.awt.Color(254, 254, 254));
        labelInformacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInformacion.setText(" ");

        jLabelUsuario.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        jLabelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelUsuario.setText(" ");

        javax.swing.GroupLayout jPanelBackgroundLayout = new javax.swing.GroupLayout(jPanelBackground);
        jPanelBackground.setLayout(jPanelBackgroundLayout);
        jPanelBackgroundLayout.setHorizontalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PrincipalDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 1154, Short.MAX_VALUE)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addGap(389, 389, 389)
                .addComponent(labelInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelBackgroundLayout.setVerticalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addComponent(PrincipalDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        menuBar.setBackground(new java.awt.Color(254, 254, 254));

        jMenuGerente.setText("Gerente");
        jMenuGerente.setVisible(false);

        jMenu10.setText("Hotel");

        jMenuItem4.setText("Registrar / Crear Hotel");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem4);

        jMenuItem5.setText("Reporte Hoteles");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem5);

        jMenuItem6.setText("Modificar Hotel");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem6);

        jMenuItem7.setText("Activar / Desactivar Hotel");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem7);

        jMenuGerente.add(jMenu10);

        jMenu12.setText("Restaurante");

        jMenuItem12.setText("Crear Restaurante");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem12);

        jMenuItem14.setText("Reporte Restaurantes");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem14);

        jMenuItem15.setText("Modificar Restaurante");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem15);

        jMenuGerente.add(jMenu12);

        jMenu13.setText("Habitacion");

        jMenuItem16.setText("Crear Habitacion");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem16);

        jMenuItem17.setText("Reporte Habitaciones");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem17);

        jMenuItem18.setText("Modificar Habitacion");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem18);

        jMenuGerente.add(jMenu13);

        jMenu11.setText("Empleado");

        jMenuItem8.setText("Crear Gerente Hotel");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem8);

        jMenuItem9.setText("Crear Gerente General");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem9);

        jMenuItem11.setText("Crear Encargado Restaurante");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem11);

        jMenuItem10.setText("Reporte Empleados");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem10);

        jMenuItem13.setText("Modificar Empleado");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem13);

        jMenuGerente.add(jMenu11);

        menuBar.add(jMenuGerente);

        jMenuHotel.setText("Hotel");
        jMenuHotel.setVisible(false);

        jMenu1.setText("Empleado");

        jMenuItemCrearUsuario.setText("Crear Usuario");
        jMenuItemCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCrearUsuario);

        jMenuItemReporte.setText("Reporte Usuarios");
        jMenuItemReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReporteActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemReporte);

        jMenuItemModificar.setText("Modificar Usuario");
        jMenuItemModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModificarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemModificar);

        jMenuItemEliminar.setText("Eliminar Usuario");
        jMenuItemEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEliminarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemEliminar);

        jMenuHotel.add(jMenu1);

        jMenu5.setText("Menu");

        jMenuItemCrearMenu.setText("Crear Menu");
        jMenuItemCrearMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearMenuActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemCrearMenu);

        jMenuItemRepMenu.setText("Reporte Menu");
        jMenuItemRepMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRepMenuActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemRepMenu);

        jMenuItemModMen.setText("Modificar Menu");
        jMenuItemModMen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModMenActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemModMen);

        jMenuItemDeshaMenu.setText("DesHabilitar Menu");
        jMenuItemDeshaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeshaMenuActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemDeshaMenu);

        jMenuHotel.add(jMenu5);

        jMenu6.setText("Habitacion");

        jMenuItemModPre.setText("Modificar Precio / Reportes");
        jMenuItemModPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModPreActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemModPre);

        jMenuHotel.add(jMenu6);

        menuBar.add(jMenuHotel);

        jMenuRecepcion.setText("Recepcion");
        jMenuRecepcion.setVisible(false);

        jMenu2.setText("Reservacion");

        jMenuItemRegistrar.setText("Reservar Habitacion");
        jMenuItemRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemRegistrar);

        jMenuItemElimRes.setText("Cancelar Reservacion");
        jMenuItemElimRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemElimResActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemElimRes);

        jMenuItemReportReser.setText("Reporte Reservaciones");
        jMenuItemReportReser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReportReserActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemReportReser);

        jMenuRecepcion.add(jMenu2);

        jMenu3.setText("Alojamiento");

        jMenuItemRegAloj.setText("Registrar Alojamiento");
        jMenuItemRegAloj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegAlojActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemRegAloj);

        jMenuItemRepAloj.setText("Reporte Alojamiento");
        jMenuItemRepAloj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRepAlojActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemRepAloj);

        jMenuItem3.setText("Reporte Alojamiento Cliente");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItemAlojHab.setText("Reporte Alojamiento Habitacion");
        jMenuItemAlojHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlojHabActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemAlojHab);

        jMenuRecepcion.add(jMenu3);

        jMenu4.setText("Cliente");

        jMenuItemRegClie.setText("Registrar Cliente");
        jMenuItemRegClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegClieActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemRegClie);

        jMenuItemModClie.setText("Modificar Cliente");
        jMenuItemModClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModClieActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemModClie);

        jMenuItemRepClie.setText("Reporte Clientes");
        jMenuItemRepClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRepClieActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemRepClie);

        jMenuRecepcion.add(jMenu4);

        jMenu8.setText("Registrar egreso");

        jMenuItem2.setText("Cobrar monto Total");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem2);

        jMenuRecepcion.add(jMenu8);

        menuBar.add(jMenuRecepcion);

        jMenuRestaurante.setText("Restaurante");
        jMenuRestaurante.setVisible(false);

        jMenu7.setText("Servicio-Habitacion");

        jMenuItemTomarPed.setText("Tomar pedido");
        jMenuItemTomarPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTomarPedActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItemTomarPed);

        jMenuRestaurante.add(jMenu7);

        jMenu9.setText("Consumo");

        jMenuItemReporCon.setText("Reporte Consumos");
        jMenuItemReporCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReporConActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItemReporCon);

        jMenuRestaurante.add(jMenu9);

        menuBar.add(jMenuRestaurante);

        jMenuOpciones.setText("Opciones");

        jMenuItemCambiar.setText("Cambiar de Usuario");
        jMenuItemCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCambiarActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemCambiar);

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemSalir);

        menuBar.add(jMenuOpciones);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 1154, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCambiarActionPerformed
        SolicitadorEmpleado se = new SolicitadorEmpleado(this, rootPaneCheckingEnabled, null);
        this.dispose();
        se.setVisible(true);
    }//GEN-LAST:event_jMenuItemCambiarActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearUsuarioActionPerformed
//        CreadorUsuario cu = new CreadorUsuario(this.DB);
//        añadirComponente(cu);
    }//GEN-LAST:event_jMenuItemCrearUsuarioActionPerformed

    private void jMenuItemReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReporteActionPerformed
//        ReporteUsuarios ru = new ReporteUsuarios(this.DB);
//        añadirComponente(ru);
    }//GEN-LAST:event_jMenuItemReporteActionPerformed

    private void jMenuItemModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModificarActionPerformed
//        ModificadorUsuario mu = new ModificadorUsuario(DB);
//        añadirComponente(mu);
    }//GEN-LAST:event_jMenuItemModificarActionPerformed

    private void jMenuItemEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEliminarActionPerformed
//        EliminadorUsuario eu = new EliminadorUsuario(DB);
//        añadirComponente(eu);
    }//GEN-LAST:event_jMenuItemEliminarActionPerformed

    private void jMenuItemRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarActionPerformed
//        RegistradorReservacion rr = new RegistradorReservacion(DB, usuario);
//        añadirComponente(rr);
    }//GEN-LAST:event_jMenuItemRegistrarActionPerformed

    private void jMenuItemReportReserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReportReserActionPerformed
//        ReporteReservaciones rr = new ReporteReservaciones(DB, usuario);
//        añadirComponente(rr);
    }//GEN-LAST:event_jMenuItemReportReserActionPerformed

    private void jMenuItemElimResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemElimResActionPerformed
//        CanceladorReservacion cr = new CanceladorReservacion(DB, usuario);
//        añadirComponente(cr);
    }//GEN-LAST:event_jMenuItemElimResActionPerformed

    private void jMenuItemRegAlojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegAlojActionPerformed
//        RegistradorAlojamiento ra = new RegistradorAlojamiento(DB, usuario);
//        añadirComponente(ra);
    }//GEN-LAST:event_jMenuItemRegAlojActionPerformed

    private void jMenuItemRepClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRepClieActionPerformed
//        ReporteClientes rc = new ReporteClientes(DB, usuario);
//        añadirComponente(rc);
    }//GEN-LAST:event_jMenuItemRepClieActionPerformed

    private void jMenuItemRegClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegClieActionPerformed
//        RegistradorCliente rc = new RegistradorCliente(DB, usuario);
//        añadirComponente(rc);
    }//GEN-LAST:event_jMenuItemRegClieActionPerformed

    private void jMenuItemCrearMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearMenuActionPerformed
//        CreadorMenu cm = new CreadorMenu(DB);
//        añadirComponente(cm);
    }//GEN-LAST:event_jMenuItemCrearMenuActionPerformed

    private void jMenuItemRepMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRepMenuActionPerformed
//        ReporteMenu rm = new ReporteMenu(DB);
//        añadirComponente(rm);
    }//GEN-LAST:event_jMenuItemRepMenuActionPerformed

    private void jMenuItemModMenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModMenActionPerformed
//        ModificadorMenu mm = new ModificadorMenu(DB);
//        añadirComponente(mm);
    }//GEN-LAST:event_jMenuItemModMenActionPerformed

    private void jMenuItemDeshaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeshaMenuActionPerformed
//        DeshabilitadorMenu dm = new DeshabilitadorMenu(DB);
//        añadirComponente(dm);
    }//GEN-LAST:event_jMenuItemDeshaMenuActionPerformed

    private void jMenuItemRepAlojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRepAlojActionPerformed
//        ReporteAlojamientos ra = new ReporteAlojamientos(DB, usuario);
//        añadirComponente(ra);
    }//GEN-LAST:event_jMenuItemRepAlojActionPerformed

    private void jMenuItemModClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModClieActionPerformed
//        ModificadorCliente mc = new ModificadorCliente(DB, usuario);
//        añadirComponente(mc);
    }//GEN-LAST:event_jMenuItemModClieActionPerformed

    private void jMenuItemModPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModPreActionPerformed
//        ModificadorPrecio mp = new ModificadorPrecio(DB, usuario);
//        añadirComponente(mp);
    }//GEN-LAST:event_jMenuItemModPreActionPerformed

    private void jMenuItemTomarPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTomarPedActionPerformed
//        TomarPedido tp = new TomarPedido(DB);
//        añadirComponente(tp);
    }//GEN-LAST:event_jMenuItemTomarPedActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
//        ReporteAlojamientosCliente rac = new ReporteAlojamientosCliente(DB, usuario);
//        añadirComponente(rac);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItemAlojHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlojHabActionPerformed
//        ReporteAlojamientosHabitacion rah = new ReporteAlojamientosHabitacion(DB, usuario);
//        añadirComponente(rah);
    }//GEN-LAST:event_jMenuItemAlojHabActionPerformed

    private void jMenuItemReporConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReporConActionPerformed
//        ReporteConsumos rc = new ReporteConsumos(DB);
//        añadirComponente(rc);
    }//GEN-LAST:event_jMenuItemReporConActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        CreadorHotel ch = new CreadorHotel();
        añadirComponente(ch);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        ReporteHotel rh = new ReporteHotel();
        añadirComponente(rh);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        ModificadorHotel mh = new ModificadorHotel();
        añadirComponente(mh);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        DesactivarActivarHotel dah = new DesactivarActivarHotel();
        añadirComponente(dah);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        CreadorGerenteH cg = new CreadorGerenteH();
        añadirComponente(cg);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        CreadorGerenteG cgg = new CreadorGerenteG();
        añadirComponente(cgg);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        ReporteEmpleados rg = new ReporteEmpleados();
        añadirComponente(rg);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        CreadorEncargadoR cer = new CreadorEncargadoR();
        añadirComponente(cer);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        CreadorRestaurante cr = new CreadorRestaurante();
        añadirComponente(cr);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        ModificadorEmpleado me = new ModificadorEmpleado(empleado);
        añadirComponente(me);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        ReporteRestaurante rr = new ReporteRestaurante();
        añadirComponente(rr);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        ModificadorRestaurante mr = new ModificadorRestaurante();
        añadirComponente(mr);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        CreadorHabitacion ch = new CreadorHabitacion();
        añadirComponente(ch);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        ReporteHabitaciones rh = new ReporteHabitaciones();
        añadirComponente(rh);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        ModificadorHabitacion mh = new ModificadorHabitacion();
        añadirComponente(mh);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    /*Metodo encargado de modificar el color del "menuBar" , asi como colocar el nombre del cliente y 
    su cargo en el hotel*/
    private void setItems() {
        int tipoImagen = 0;
        int tipoImagen1 = 0;
        if (empleado.getTipo() == 1) {
            tipoImagen = 1;
            tipoImagen1 = 2;
            tipoUsuario = "Gerente General: ";
        } else if (empleado.getTipo() == 2) {
            tipoImagen = 1;
            tipoImagen1 = 2;
            tipoUsuario = "Gerente Hotel: ";
        } else if (empleado.getTipo() == 3) {
            tipoImagen = 3;
            tipoImagen1 = 4;
            tipoUsuario = "Recepcionista: ";
        } else {
            tipoImagen = 5;
            tipoImagen1 = 6;
            tipoUsuario = "Encargado de Restaurante: ";
        }
        this.path = BACKGROUNDD_IMAGE_PARENT_RELATIVE_PATH + tipoImagen + IMAGE_EXTENSION;
        this.path1 = BACKGROUNDD_IMAGE_PARENT_RELATIVE_PATH + tipoImagen1 + IMAGE_EXTENSION;
    }

    /**
     * Metodo encargado de añadir un nuevo componente al escritorio principal
     *
     * @param component
     */
    private void añadirComponente(Component component) {
        PrincipalDesktop.add(component);
        Dimension desktopSize = PrincipalDesktop.getSize();
        Dimension FrameSize = component.getSize();
        component.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - desktopSize.height) / 2);
        component.show();
    }

    private void visualizarItems() {
        if (empleado.getTipo() == 1) {
            jMenuGerente.setVisible(true);
            this.labelInformacion.setText("GERENCIA");
        } else if (empleado.getTipo() == 2) {
            jMenuHotel.setVisible(true);
            this.labelInformacion.setText("HOTEL \"" + empleado.getNombreHotel() + "\"");
        } else if(empleado.getTipo() == 3) {
            jMenuRecepcion.setVisible(true);
            this.labelInformacion.setText("RECEPCION \"" + empleado.getNombreHotel() + "\"");
        } else {
            jMenuRestaurante.setVisible(true);
            this.labelInformacion.setText("RESTAURANTE \"" + empleado.getNombreRestaurante() + " \"");
        }
        this.jLabelUsuario.setText(tipoUsuario + this.empleado.getNombre());
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane PrincipalDesktop;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenu jMenuGerente;
    private javax.swing.JMenu jMenuHotel;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemAlojHab;
    private javax.swing.JMenuItem jMenuItemCambiar;
    private javax.swing.JMenuItem jMenuItemCrearMenu;
    private javax.swing.JMenuItem jMenuItemCrearUsuario;
    private javax.swing.JMenuItem jMenuItemDeshaMenu;
    private javax.swing.JMenuItem jMenuItemElimRes;
    private javax.swing.JMenuItem jMenuItemEliminar;
    private javax.swing.JMenuItem jMenuItemModClie;
    private javax.swing.JMenuItem jMenuItemModMen;
    private javax.swing.JMenuItem jMenuItemModPre;
    private javax.swing.JMenuItem jMenuItemModificar;
    private javax.swing.JMenuItem jMenuItemRegAloj;
    private javax.swing.JMenuItem jMenuItemRegClie;
    private javax.swing.JMenuItem jMenuItemRegistrar;
    private javax.swing.JMenuItem jMenuItemRepAloj;
    private javax.swing.JMenuItem jMenuItemRepClie;
    private javax.swing.JMenuItem jMenuItemRepMenu;
    private javax.swing.JMenuItem jMenuItemReporCon;
    private javax.swing.JMenuItem jMenuItemReportReser;
    private javax.swing.JMenuItem jMenuItemReporte;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenuItem jMenuItemTomarPed;
    private javax.swing.JMenu jMenuOpciones;
    private javax.swing.JMenu jMenuRecepcion;
    private javax.swing.JMenu jMenuRestaurante;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JLabel labelInformacion;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
