/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package comerdormir.frontend;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import project.frontend.empleado.SolicitadorEmpleado;
import project.frontend.hotel.ReporteHotel;
import project.frontend.opinion.CreadorOpinionHotel;
import project.frontend.opinion.CreadorOpinionRestaurante;
import project.frontend.reservacion.RegistradorReservacion;

/**
 *
 * @author fabricio
 */
public class MenuPrincipal extends javax.swing.JFrame {

    public String path;
    public String path1;
    private final static String BACKGROUNDD_IMAGE_PARENT_RELATIVE_PATH ="src/project/frontend/images/ComerDormir.jpg";
    private final static String BACKGROUNDD_IMAGE_PARENT_RELATIVE_PATH1 ="src/project/frontend/images/ComerDormir2.jpg";
    
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        path = BACKGROUNDD_IMAGE_PARENT_RELATIVE_PATH;
        path1 = BACKGROUNDD_IMAGE_PARENT_RELATIVE_PATH1;
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                ImageIcon im = new ImageIcon(path1);
                Image i = im.getImage();
                g.drawImage(i, 0, 0, this.getSize().width, this.getSize().height, this);
            }
        };
        jButtonReservar = new javax.swing.JButton();
        jButtonHotel = new javax.swing.JButton();
        jButtonRestaurante = new javax.swing.JButton();
        jButtonHotel1 = new javax.swing.JButton();
        PrincipalDesktop = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                ImageIcon im = new ImageIcon(path);
                Image i = im.getImage();
                g.drawImage(i, 0, 0, this.getSize().width, this.getSize().height, this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemIngresar = new javax.swing.JMenuItem();
        jMenuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonReservar.setBackground(new java.awt.Color(254, 254, 254));
        jButtonReservar.setFont(new java.awt.Font("Caviar Dreams", 0, 18)); // NOI18N
        jButtonReservar.setForeground(new java.awt.Color(1, 27, 111));
        jButtonReservar.setText("Reservar Habitacion");
        jButtonReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReservarActionPerformed(evt);
            }
        });

        jButtonHotel.setBackground(new java.awt.Color(254, 254, 254));
        jButtonHotel.setFont(new java.awt.Font("Caviar Dreams", 0, 18)); // NOI18N
        jButtonHotel.setForeground(new java.awt.Color(1, 27, 111));
        jButtonHotel.setText("Calificar Hotel");
        jButtonHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHotelActionPerformed(evt);
            }
        });

        jButtonRestaurante.setBackground(new java.awt.Color(254, 254, 254));
        jButtonRestaurante.setFont(new java.awt.Font("Caviar Dreams", 0, 18)); // NOI18N
        jButtonRestaurante.setForeground(new java.awt.Color(1, 27, 111));
        jButtonRestaurante.setText("Calificar Restaurante");
        jButtonRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestauranteActionPerformed(evt);
            }
        });

        jButtonHotel1.setBackground(new java.awt.Color(254, 254, 254));
        jButtonHotel1.setFont(new java.awt.Font("Caviar Dreams", 0, 18)); // NOI18N
        jButtonHotel1.setForeground(new java.awt.Color(1, 27, 111));
        jButtonHotel1.setText("Hoteles");
        jButtonHotel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHotel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonHotel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonReservar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRestaurante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonHotel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButtonReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButtonHotel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButtonHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButtonRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(336, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PrincipalDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 1072, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PrincipalDesktop)
        );

        jMenuBar1.setBackground(new java.awt.Color(254, 254, 254));

        jMenu2.setText("Opciones");

        jMenuItemIngresar.setText("Ingresar al Sistema");
        jMenuItemIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIngresarActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemIngresar);

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemSalir);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed
 
    private void añadirComponente(Component component) {
        PrincipalDesktop.add(component);
        Dimension desktopSize = PrincipalDesktop.getSize();
        Dimension FrameSize = component.getSize();
        component.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - desktopSize.height) / 2);
        component.show();
    }
    
    private void jMenuItemIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIngresarActionPerformed
        SolicitadorEmpleado se = new SolicitadorEmpleado(this, rootPaneCheckingEnabled, this);
        se.setVisible(true);
    }//GEN-LAST:event_jMenuItemIngresarActionPerformed

    private void jButtonReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservarActionPerformed
        RegistradorReservacion rr = new RegistradorReservacion();
        añadirComponente(rr);
    }//GEN-LAST:event_jButtonReservarActionPerformed

    private void jButtonHotel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHotel1ActionPerformed
        ReporteHotel rh = new ReporteHotel();
        añadirComponente(rh);
    }//GEN-LAST:event_jButtonHotel1ActionPerformed

    private void jButtonHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHotelActionPerformed
        CreadorOpinionHotel coh = new CreadorOpinionHotel();
        añadirComponente(coh);
    }//GEN-LAST:event_jButtonHotelActionPerformed

    private void jButtonRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestauranteActionPerformed
        CreadorOpinionRestaurante cor = new CreadorOpinionRestaurante();
        añadirComponente(cor);
    }//GEN-LAST:event_jButtonRestauranteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane PrincipalDesktop;
    private javax.swing.JButton jButtonHotel;
    private javax.swing.JButton jButtonHotel1;
    private javax.swing.JButton jButtonReservar;
    private javax.swing.JButton jButtonRestaurante;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemIngresar;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
